#!/usr/bin/env python3
"""
DayZ Config.cpp Generator
Generates basic config.cpp files for new mods.
"""

import sys
from pathlib import Path

class ConfigGenerator:
    def __init__(self, mod_name, author):
        self.mod_name = mod_name
        self.author = author
        
    def generate_config(self):
        """Generate a config.cpp file"""
        config = f"""// {self.mod_name} Configuration
// Generated by DayZ Config Generator
// Author: {self.author}

class CfgPatches
{{
    class {self.mod_name}
    {{
        units[] = {{}};
        weapons[] = {{}};
        requiredVersion = 0.1;
        requiredAddons[] = {{"DZ_Data", "DZ_Scripts"}};
    }};
}};

class CfgMods
{{
    class {self.mod_name}
    {{
        dir = "{self.mod_name}";
        picture = "";
        action = "";
        hideName = 1;
        hidePicture = 1;
        name = "{self.mod_name}";
        credits = "{self.author}";
        author = "{self.author}";
        authorID = "0";
        version = "1.0";
        extra = 0;
        type = "mod";
        
        dependencies[] = {{"Game", "World", "Mission"}};
        
        class defs
        {{
            class gameScriptModule
            {{
                value = "";
                files[] = {{"{self.mod_name}/scripts/3_Game"}};
            }};
            class worldScriptModule
            {{
                value = "";
                files[] = {{"{self.mod_name}/scripts/4_World"}};
            }};
            class missionScriptModule
            {{
                value = "";
                files[] = {{"{self.mod_name}/scripts/5_Mission"}};
            }};
        }};
    }};
}};

class CfgVehicles
{{
    // Add your custom items, clothing, weapons, etc. here
    
    /*
    // Example: Custom clothing item
    class Clothing_Base;
    class {self.mod_name}_CustomShirt : Clothing_Base
    {{
        scope = 2;
        displayName = "Custom Shirt";
        descriptionShort = "A custom shirt";
        model = "\\{self.mod_name}\\data\\shirt.p3d";
        weight = 500;
        itemSize[] = {{3,2}};
        itemsCargoSize[] = {{4,3}};
        
        class DamageSystem
        {{
            class GlobalHealth
            {{
                class Health
                {{
                    hitpoints = 100;
                }};
            }};
        }};
    }};
    */
}};

class CfgWeapons
{{
    // Add your custom weapons here
    
    /*
    // Example: Custom weapon
    class Rifle_Base;
    class {self.mod_name}_CustomRifle : Rifle_Base
    {{
        scope = 2;
        displayName = "Custom Rifle";
        descriptionShort = "A custom rifle";
        model = "\\{self.mod_name}\\data\\rifle.p3d";
        weight = 3500;
        itemSize[] = {{8,3}};
    }};
    */
}};
"""
        return config
    
    def generate_mod_structure(self, output_dir):
        """Generate complete mod directory structure"""
        base_path = Path(output_dir) / self.mod_name
        
        # Create directories
        directories = [
            base_path,
            base_path / "scripts" / "3_Game",
            base_path / "scripts" / "4_World",
            base_path / "scripts" / "5_Mission",
            base_path / "data",
        ]
        
        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)
        
        # Generate config.cpp
        config_path = base_path / "config.cpp"
        with open(config_path, 'w') as f:
            f.write(self.generate_config())
        
        print(f"✅ Generated mod structure at: {base_path}")
        print(f"✅ Created config.cpp")
        print(f"\nDirectory structure:")
        print(f"  {self.mod_name}/")
        print(f"    ├── config.cpp")
        print(f"    ├── scripts/")
        print(f"    │   ├── 3_Game/")
        print(f"    │   ├── 4_World/")
        print(f"    │   └── 5_Mission/")
        print(f"    └── data/")
        print(f"\nNext steps:")
        print(f"1. Add your script files to the scripts/ directories")
        print(f"2. Add your models and textures to the data/ directory")
        print(f"3. Update config.cpp with your custom items")
        print(f"4. Build the mod using Addon Builder")

def main():
    if len(sys.argv) < 3:
        print("DayZ Config.cpp Generator")
        print("=" * 50)
        print("\nUsage: python config-generator.py <mod_name> <author> [output_dir]")
        print("\nExample:")
        print("  python config-generator.py MyMod 'John Doe' ./mods")
        print("\nThis will generate:")
        print("  - Complete mod directory structure")
        print("  - config.cpp with basic configuration")
        print("  - Script directories (3_Game, 4_World, 5_Mission)")
        sys.exit(1)
    
    mod_name = sys.argv[1]
    author = sys.argv[2]
    output_dir = sys.argv[3] if len(sys.argv) > 3 else "."
    
    # Validate mod name (no spaces or special chars)
    if not mod_name.replace('_', '').replace('-', '').isalnum():
        print("❌ Error: Mod name should only contain letters, numbers, underscores, and hyphens")
        sys.exit(1)
    
    generator = ConfigGenerator(mod_name, author)
    generator.generate_mod_structure(output_dir)

if __name__ == "__main__":
    main()
